### ISSUE TITLE
hamming distance?

### ISSUE THREAD

**Issue by npgauth** [PAIR-code/umap-js#14]
Great piece of code - a useful find for our work -- thank you!!

One question: the readme states that the code only works with Euclidean distance. Is it possible for us to replace the "euclidean" function with a hamming distance function, or will that not work for some reason?

Thanks! Nick

**Comment by cannoneyed** [comment]
Hey @npgauth - Thanks and glad you're finding it useful. I meant to add custom distance functions but never got around to it... I'll try to update the lib shortly to add the ability to construct a UMAP instance with a custom distance function

**Comment by cannoneyed** [comment]
https://github.com/PAIR-code/umap-js/pull/15, should be merged / built shortly!

**Comment by npgauth** [comment]
Very cool. I'll try it out shortly. Thanks @cannoneyed !!
