### ISSUE TITLE
Is the 'getCSR' method for the SparseMatrix incorrect?

### ISSUE THREAD

**Issue by ProductiveRage** [PAIR-code/umap-js#22]
I was having a poke around in the code here and I noticed something that looked a bit odd to me about the 'getCSR' method for the SparseMatrix - when it sorts the entries by row and column, it does this:

```
entries.sort((a, b) => {
    if (a.row === b.row) {
        return a.col - b.col;
    } else {
        return a.row - b.col;
    }
});
```

.. this looked like it was intended to say "sort the entries by row and then by column" but the code to do that would look like this:

```
entries.sort((a, b) => {
    if (a.row === b.row) {
        return a.col - b.col;
    } else {
        return a.row - b.row; // Note: This line changed
    }
});
```

There is a unit test for this method, so I thought that I'd look there to see if it could help me understand what's going but it's only confused me more! The test method 'getCSR' tests against a 3x3 matrix that is fully populated -

```
const rows = [0, 0, 0, 1, 1, 1, 2, 2, 2];
const cols = [0, 1, 2, 0, 1, 2, 0, 1, 2];
const vals = [1, 2, 3, 4, 5, 6, 7, 8, 9];
const dims = [3, 3];
A = new SparseMatrix(rows, cols, vals, dims);
```

.. which looks like this:

```
1 2 3
4 5 6
7 8 9
```

And so the CSR representation would have values `1 2 3 4 5 6 7 8 9` and indices `0 1 2 0 1 2 0 1 2` and indptr `0 3 6`, shouldn't it? (Possibly indptr `0 3 6 9` to enable slicing into rows).

The unit test actually expects values `1, 2, 3, 7, 4, 5, 6, 8, 9` and indices `0, 1, 2, 0, 0, 1, 2, 1, 2` and indptr `0, 3, 4, 7` and the test passes. Is the test correct, though??

I must confess that I wasn't familiar with the CSR format before looking into your code, so it's very possible that I've got the wrong end of the stick. To try to get my head around it, I've been looking at the description for [scipy.sparse.csr_matrix](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.sparse.csr_matrix.html) page and at this [YouTube video](https://www.youtube.com/watch?v=Qi7FcjN7nsc).

**Comment by cannoneyed** [comment]
Hey! Thanks for digging into this - I'm on paternity leave right now so I'm not 100% in the loop, but I'll have a peek at this later today or tomorrow. I have to admit, there's a very large chance that I messed something up here as I was pretty much just porting over the scipy logic (and confusing myself quite a bit in the process!)

Anyway, will take a look and feel free to open up a PR if you figure anything out definitively!

**Comment by ProductiveRage** [comment]
No problem! I _think_ that I've got it right, so hopefully I can open up a PR. There's definitely no rush since you'll have more important things on your hard on paternity! :)

**Comment by cannoneyed** [comment]
Looks like you've got this right. Feel free to open up a PR or I'll get around to it shortly!

**Comment by ProductiveRage** [comment]
Great - I'll get a PR over to you soon!

**Comment by cannoneyed** [comment]
FYI I've opened up a quick PR for this in https://github.com/PAIR-code/umap-js/pull/25, thanks for finding it!

**Comment by ProductiveRage** [comment]
Sorry, I completely forgot about this! Thanks for tackling it :)
