### ISSUE TITLE
flattenTree throws error if tree is a leaf

### ISSUE THREAD

**Issue by brianchirls** [PAIR-code/umap-js#31]
See the following [code](https://github.com/PAIR-code/umap-js/blob/f9b319b91ec054ef4003c4667cf4dd820b1ed9a9/src/tree.ts#L243-L245) inside `flattenTree`:

```typescript
  const hyperplanes = utils
    .range(nNodes)
    .map(() => utils.zeros(tree.hyperplane!.length));
```

When a tree is created in `makeEuclideanTree`, if the number of vectors is not greater than the leaf size, `tree.hyperplane` is undefined. I see the typescript code checks for that with a Non-null assertion operator, but the [transpiled JS](https://unpkg.com/umap-js@1.3.1/lib/umap-js.js) code does not:

```javascript
    var hyperplanes = utils
        .range(nNodes)
        .map(function () { return utils.zeros(tree.hyperplane.length); });
```

Perhaps there is a problem with the typescript configuration?

**Comment by kevinrobinson** [comment]
fwiw, I think the type compilation issue is the same thing mentioned in https://github.com/PAIR-code/umap-js/pull/27:

> Separately, it looks like the TS on that line has a non-null constraint exactly at that point, so it seems like there might be a type bug somehow too. I'm not sure if that's relevant point out, and I didn't look at that further but here's a [link](https://github.com/PAIR-code/umap-js/blob/master/src/tree.ts#L242) if that rings any bells.

**Comment by brianchirls** [comment]
That sounds right. Doesn't look like the solution to #27 addressed it though. I'm sorry I don't know enough about Typescript to offer a pull request.

**Comment by cannoneyed** [comment]
Thanks for bringing this up and sorry for the delay in getting back to you (was just on paternity leave for the last few months). Anyway, I've glanced quickly at it and the issue makes sense if `tree.hyperplane` is undefined - It's a simple enough fix but I'd just like to be sure I can reproduce it correctly. Mind letting me know under what conditions you're encountering the error?

**Comment by brianchirls** [comment]
No worries. Congrats!

I believe it happens when the number of embeddings/vectors is very small, i.e. small enough that a tree is not created.

**Comment by cannoneyed** [comment]
Fixed with https://github.com/PAIR-code/umap-js/pull/33
