### ISSUE TITLE
Retrieve connectivity

### ISSUE THREAD

**Issue by higsch** [PAIR-code/umap-js#39]
Thanks for this awesome tool!

Is there a way to extract connectivity information from the embedding? I would like to draw the underlying graph as well.
Something compared to `umap.plot.connectivity` in the Python implementation [here](https://umap-learn.readthedocs.io/en/latest/plotting.html).

**Comment by cannoneyed** [comment]
Hello @higsch!

There's not an immediate way to pull that out of the current implementation... umap python has evolved quite a bit in the interim since I published this version, and I haven't been particularly diligent in keeping up-to-date with the awesome work going on over there.

**Comment by higsch** [comment]
No worries, completely fine! Keep up the good work!
