### ISSUE TITLE
transform api call not returning

### ISSUE THREAD

**Issue by seenanair** [PAIR-code/umap-js#42]
I am using umap library for my project.  umap.fit and other methods are working fine. But when I  transform additional points after fitting, by calling umap.transform, it is hanging and not returning any value. The dataset I am trying is a simple one with less than 50 rows. Any help would be much appreciated.

**Comment by LrsChrSch** [comment]
Did you solve this? Having the same issue. Fitting with a list of 512-item-arrays is no problem. But transforming a single 512-item-array afterwards seems to crash the site.

**Comment by seenanair** [comment]
I used 'fitAsync' eventually and that worked

**Comment by LrsChrSch** [comment]
Managed to find my issue as well. I used a different random method from the seedrandom package to create my umap object. Worked fine during fitting, but apparently breaks stuff as soon as you try to transform anything with it.

Thanks for your quick reply though!
